# Generated by Django 6.0.5 on 2026-06-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('service_required', models.CharField(blank=True, max_length=100, null=True)),
                ('budget', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Pankaj Patel', max_length=100)),
                ('title', models.CharField(default='Founder & Principal Developer', max_length=255)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='founder/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('achievements', models.JSONField(blank=True, default=list, help_text='List of achievements')),
                ('roles', models.JSONField(blank=True, default=list, help_text="List of dynamic typing roles, e.g. ['Full Stack Developer', 'React Developer']")),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Frontend', 'Frontend Development'), ('Backend', 'Backend Development'), ('Full Stack', 'Full Stack Development'), ('Mobile App', 'Mobile Development'), ('AI', 'AI Integration')], default='Full Stack', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('technologies', models.JSONField(default=list, help_text='List of technology names')),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('icon_name', models.CharField(help_text='React Icon name or Lucide name, e.g. FaLaptopCode, FaReact, FaServer', max_length=50)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='SiteeForgeStudio', max_length=255)),
                ('tagline', models.CharField(default='Building Modern Digital Experiences', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site_assets/')),
                ('email', models.EmailField(default='contact@siteeforgestudio.com', max_length=254)),
                ('phone', models.CharField(default='+919876543210', max_length=20)),
                ('whatsapp_number', models.CharField(default='+919876543210', max_length=20)),
                ('address', models.TextField(default='India')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('about_text', models.TextField(blank=True, null=True)),
                ('mission', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('why_choose_us', models.JSONField(blank=True, default=list, help_text="List of reasons, e.g. ['Modern UI/UX', 'Responsive Design']")),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Tools', 'Tools'), ('AI & Automation', 'AI & Automation')], max_length=50)),
                ('proficiency', models.PositiveIntegerField(default=80, help_text='Proficiency percentage (0-100)')),
                ('icon_name', models.CharField(blank=True, help_text='Icon name, e.g. DiReact, DiPython', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(help_text='React Icon name, e.g. FaGithub, FaLinkedin', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_role', models.CharField(max_length=100)),
                ('client_company', models.CharField(blank=True, max_length=100, null=True)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('feedback', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='Rating between 1 and 5')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
